name: packaging

on:
  # pull_request:
  #   branches:
  #     - master
  workflow_dispatch:
    branches:
      - master
    inputs:
      release_tag:
        description: '发布tag'
        required: true

jobs:      
  mambaforge:
    name: mambaforge (${{ matrix.os }}, Mambaforge)
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu", "macos", "windows"]
        include:
          - os: ubuntu
            miniforge-variant: Mambaforge
          - os: macos
            miniforge-variant: Mambaforge
          - os: windows
            miniforge-variant: Mambaforge
    steps:
      # - name: create_release
      #   # id: create_release
      #   if: runner.os == 'Linux'
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   with:
      #     tag_name: ${{ github.event.inputs.release_tag }}
      #     release_name: 发布 ${{ github.event.inputs.release_tag }}

      - name: Checkout master
        uses: actions/checkout@v2
        with:
          ref: main
      - uses: conda-incubator/setup-miniconda@v2
        with:
          condarc-file: ${{ matrix.condarc-file }}
          miniforge-variant: ${{ matrix.miniforge-variant }}
          miniforge-version: ${{ matrix.miniforge-version }}
          use-mamba: true

      - name: Install dependencies
        if runner.os == 'ubuntu':
          run: source /home/runner/.bashrc
        else if runner.os == 'macos':
          run: source /Users/runner/.bash_profile
        else:
          run: bash

      - name: pack
        run: |
          conda activate potatoCAD
          python -m pip install --upgrade pip
          pip install -r ./requirements-pip.txt
          mamba install --yes --file ./requirements-conda.txt 
          mamba install -c conda-forge conda-pack
          conda pack -n potatoCAD -o environment-${{ matrix.os }}.zip --zip-symlinks
          
      - name: Upload the artifacts
        uses: AButler/upload-release-assets@v2.0
        with:
          # release_tag: ${{ steps.create_release.outputs.id }}
          # release_id: ${{ steps.create_release.outputs.id }}
          release-tag: ${{ github.event.inputs.release_tag }}
          files: 'environment-*'
          repo-token: ${{ secrets.GITHUB_TOKEN }}